### ISSUE TITLE
JSON API over TLS

### ISSUE THREAD

**Issue by heruan** [coova/coova-chilli#452]
How can I enable SSL for the JSON API (i.e. port 3990)? `HS_UAMUISSL=on` seems to do the trick for the UI, not the JSON API.

Thank you!

**Comment by irongomme** [comment]
You will need to use those options : 

```
UAMUIPORT=3990
UAMUIPORT=3991
UAMUISSL
UAMALIASNAME=nas
UAMALIASIP=1.0.0.1
DOMAIN=mydomain.test
SSLCERTFILE=/path/to/my/certificate.crt
SSLKEYFILE=/path/to/my/certificate.key
```

Your certificate have to be valid.

Then you can call : https://nas.mydomain.test/json/status for exemple.

**Comment by irongomme** [comment]
Yes it was error for the ports, i've fixed it ! 

Does the login page is hosted on router or externally on a server?

For my use : 
- I'm using a non existing domain for chilli (ie: mybox.local)
- Your uamaliasip is the same than your dns .... and your uamlisten ... strange !  the uamaliasip is used only by coova to resolve internal domains like above (nas.mybox.local). You can try with 1.0.0.1

**Comment by heruan** [comment]
Thank you Jérôme, I was finally able to make it work! I was confused since there is no setting for the SSL port. Is port 443 hardcoded in CoovaChilli source? Plus, during runtime I can't see port 443 listening (using `ss -lnt`) nor I see iptables rules so it's still pretty much a mystery how this is handled!

**Comment by 12e1121** [comment]
@irongomme Can you please advise if the SSL is Self-signed and I am using IP address only? `Ex: https://192.168.0.5:3990/json/status ` is not working in this case.

**Comment by heruan** [comment]
@12e1121 The browser must trust the certificate, so if you use a self-signed one you need to add it manually to the browser trusted certificates.

**Comment by 12e1121** [comment]
@heruan Added but still no luck. Not sure which part having error. Could you please advise?

```
HS_WANIF=eth0
HS_LANIF=wlan0
HS_NETWORK=192.168.0.0
HS_NETMASK=255.255.255.0
HS_UAMLISTEN=192.168.0.1
HS_REDSSL=on
HS_SSLKEYFILE=/path/to/key/key.key # self-signed
HS_SSLCERTFILE=/path/to/cert/cert.cert
HS_UAMPORT=3990
HS_UAMUIPORT=4990
HS_COAPORT=3799
HS_TCP_PORTS="80 443"
# OpenDNS Servers
HS_DNS1=208.67.222.222
HS_DNS2=208.67.220.220
HS_UAMSERVER=$HS_UAMLISTEN
HS_UAMFORMAT=https://192.168.0.5:443
HS_UAMHOMEPAGE=$HS_UAMFORMAT
```

**Comment by heruan** [comment]
Try adding `HS_UAMALIASNAME=192.168.0.5`.

**Comment by 12e1121** [comment]
@heruan Unfortunately it is still not working. I try to debug on my Captive Portal and it seems that ChilliController.ssl is returning false. That is weird. Do you got any idea ?

**Comment by nzamps** [comment]
Check these are as below:

Check these:

HS_UAMUISSL=on  
HS_REDIRSSL=on

**Comment by 12e1121** [comment]
@nzamps I double confirmed those parameters were set in my config file but still no luck. Here is my full list.
```

HS_WANIF=eth0
HS_LANIF=wlan0
HS_NETWORK=192.168.0.0
HS_NETMASK=255.255.255.0
HS_UAMLISTEN=192.168.0.1
HS_UAMALIASNAME=192.168.0.1
HS_REDIRSSL=on
HS_UAMUISSL=on
HS_SSLKEYFILE=/path/to/key/key.key # self-signed
HS_SSLCERTFILE=/path/to/cert/cert.cert # self-signed 
HS_UAMPORT=3990
HS_UAMUIPORT=4990
HS_COAPORT=3799
HS_TCP_PORTS="80 443"
# OpenDNS Servers
HS_DNS1=208.67.222.222
HS_DNS2=208.67.220.220
HS_UAMSERVER=$HS_UAMLISTEN
HS_UAMFORMAT=https://192.168.0.1:443
HS_UAMHOMEPAGE=$HS_UAMFORMAT
```

And i restarted all services 
```
sudo /etc/init.d/nginx restart
sudo /etc/init.d/chilli restart
```

**Comment by htnghia90** [comment]
hi @12e1121 
I configure like that but it isn't work. I can show status http://10.1.0.1:3990/json/status but https not allow
Here is my configure . It is tp link archer C7

**/etc/chilli/default**
HS_WANIF=eth0.2
HS_LANIF=br-lan
HS_NETWORK=10.1.0.0
HS_NETMASK=255.255.255.0
HS_UAMLISTEN=10.1.0.1
HS_UAMALIASNAME=10.1.0.1
HS_REDIRSSL=on
HS_UAMUISSL=on
HS_SSLKEYFILE=/etc/ssl/mycert.key # self-signed
HS_SSLCERTFILE=/etc/ssl/mycert.cert # self-signed 
HS_UAMPORT=3990
HS_UAMUIPORT=4990
HS_COAPORT=3799
HS_TCP_PORTS="80 443"
# OpenDNS Servers
HS_DNS1=208.67.222.222
HS_DNS2=208.67.220.220

HS_NASID=nas01
HS_UAMALIASNAME=chilli
HS_UAMSERVER=$HS_UAMLISTEN
#HS_UAMFORMAT=https://\$HS_UAMLISTEN:\$HS_UAMUIPORT/www/login.chi
HS_UAMFORMAT=https://10.1.0.1:443
HS_UAMHOMEPAGE=$HS_UAMFORMAT
#HS_UAMHOMEPAGE=https://\$HS_UAMLISTEN:\$HS_UAMPORT/www/coova.html
HS_MODE=hotspot
HS_TYPE=coovachilli
HS_WWWDIR=/etc/chilli/www
HS_WWWBIN=/etc/chilli/wwwsh
HS_PROVIDER=Coova
HS_PROVIDER_LINK=http://coova.github.io/
HS_LOC_NAME="My HotSpot"	   # WISPr Location Name and used in portal


**configure uhttp**
# Server configuration
config uhttpd main

	# HTTP listen addresses, multiple allowed
	list listen_http	0.0.0.0:80
	list listen_http	[::]:80

	# HTTPS listen addresses, multiple allowed
	list listen_https	0.0.0.0:443
	list listen_https	[::]:443

	# Redirect HTTP requests to HTTPS if possible
	option redirect_https	1

	# Server document root
	option home		/www

	# Reject requests from RFC1918 IP addresses
	# directed to the servers public IP(s).
	# This is a DNS rebinding countermeasure.
	option rfc1918_filter 1

	# Maximum number of concurrent requests.
	# If this number is exceeded, further requests are
	# queued until the number of running requests drops
	# below the limit again.
	option max_requests 3

	# Maximum number of concurrent connections.
	# If this number is exceeded, further TCP connection
	# attempts are queued until the number of active
	# connections drops below the limit again.
	option max_connections 100

	# Certificate and private key for HTTPS.
	# If no listen_https addresses are given,
	# the key options are ignored.
#	option cert		/etc/uhttpd.crt
#	option key		/etc/uhttpd.key

        option cert             /etc/ssl/mycert.crt
        option key              /etc/ssl/mycert.key

	# CGI url prefix, will be searched in docroot.
	# Default is /cgi-bin
	option cgi_prefix	/cgi-bin

	# List of extension->interpreter mappings.
	# Files with an associated interpreter can
	# be called outside of the CGI prefix and do
	# not need to be executable.
#	list interpreter	".php=/usr/bin/php-cgi"
#	list interpreter	".cgi=/usr/bin/perl"

	# Lua url prefix and handler script.
	# Lua support is disabled if no prefix given.
	option lua_prefix	/luci
	option lua_handler	/usr/lib/lua/luci/sgi/uhttpd.lua

	# Specify the ubus-rpc prefix and socket path.
#	option ubus_prefix	/ubus
#	option ubus_socket	/var/run/ubus.sock

	# CGI/Lua timeout, if the called script does not
	# write data within the given amount of seconds,
	# the server will terminate the request with
	# 504 Gateway Timeout response.
	option script_timeout	60

	# Network timeout, if the current connection is
	# blocked for the specified amount of seconds,
	# the server will terminate the associated
	# request process.
	option network_timeout	30

	# HTTP Keep-Alive, specifies the timeout for persistent
	# HTTP/1.1 connections. Setting this to 0 will disable
	# persistent HTTP connections.
	option http_keepalive	20

	# TCP Keep-Alive, send periodic keep-alive probes
	# over established connections to detect dead peers.
	# The value is given in seconds to specify the
	# interval between subsequent probes.
	# Setting this to 0 will disable TCP keep-alive.
	option tcp_keepalive	1

	# Basic auth realm, defaults to local hostname
#	option realm	OpenWrt

	# Configuration file in busybox httpd format
#	option config	/etc/httpd.conf

	# Do not follow symlinks that point outside of the
	# home directory.
#	option no_symlinks	0

	# Do not produce directory listings but send 403
	# instead if a client requests an url pointing to
	# a directory without any index file.
#	option no_dirlists	0

	# Do not authenticate any ubus-rpc requests against
	# the ubus session/access procedure.
	# This is dangerous and should be always left off
	# except for development and debug purposes!
#	option no_ubusauth	0

	# For this instance of uhttpd use the listed httpauth
	# sections to require Basic auth to the specified
	# resources.
#	list httpauth prefix_user


# Defaults for automatic certificate and key generation
config cert defaults

	# Validity time
	option days		730

	# RSA key size
	option bits		2048

	# Location
	option country		ZZ
	option state		Somewhere
	option location		Unknown

	# Common name
	option commonname	'OpenWrt'

# config httpauth prefix_user
#	option prefix /protected/url/path
#	option username user
#	option password 'plaintext_or_md5_or_$p$user_for_system_user'

**I create https certificate follow this link**
https://openwrt.org/docs/guide-user/luci/getting-rid-of-luci-https-certificate-warnings

Could you take a look for me please.Thanks so much

**Comment by irongomme** [comment]
I really recommand to use a real certificate with a specific dedicated domain for json api over tls, and not a self signed certificate !
This is easy to obtain one with letsencrypt.

**Comment by 12e1121** [comment]
@irongomme @nzamps @heruan Thanks for your help. I managed to run the JSON API over https via the configuration. (Need to accept an ugly self-signed browser certificates though) I found out my problem is certs location is not correct. 

@htnghia90 Try debug using `sudo chilli -fd -c /etc/chilli.conf`.

**Comment by htnghia90** [comment]
Hi @12e1121 
Do you have another way to check that. Because AP doesn't listen https, so any reply form AP to client ( my laptop ) when my laptop sent request to https 
chilli -fd -c /etc/chilli.conf  don't show anything because don't listen https:10.1.0.1:3990
When laptop open https://10.1.0.1:3990 . It notice time out. 
How do you create certificate. Could you give me link for create new certificate. I think I have problem with that
Thanks you
